version: '3.8'

services:
  # Nginx web-server
  nginx:
    build:
      context: ./.docker/
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - 80:80
    volumes:
      - ./src/:/var/www/
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    networks:
      - sheep_network

  # Admin laravel project
  laravel:
    build:
      context: ./
      dockerfile: ./.docker/php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./src:/var/www/
      - ./.docker/php/entrypoint.sh:/var/www/entrypoint.sh
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - mysql
    networks:
      - sheep_network

  # MySQL database server
  mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sheep_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
    volumes:
      - ./storage/dbdata/:/var/lib/mysql/
    networks:
      - sheep_network

  # PHP My Admin
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8083:80
    links:
      - mysql
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql
    networks:
      - sheep_network


volumes:
  cache:
    driver: local

networks:
  sheep_network:
    driver: bridge